import type { Question } from "./types";

// Wording and phase/category mappings are the specified questionnaire.
// Phase labels belong to the data/scoring layer, never the question UI.
export const QUESTIONS: readonly Question[] = [
  { id: 1, text: "Jag har ofta en stark drivkraft att utvecklas, förbättra saker och komma framåt.", element: "wood", category: "constitution" },
  { id: 2, text: "Jag blir lätt frustrerad när planer stoppas eller när jag känner mig begränsad.", element: "wood", category: "stress" },
  { id: 3, text: "Jag tycker om att planera, sätta mål och se en tydlig riktning framåt.", element: "wood", category: "constitution" },
  { id: 4, text: "När jag är stressad blir jag lätt spänd i kroppen, exempelvis i nacke, axlar eller käkar.", element: "wood", category: "stress" },
  { id: 5, text: "Regelbunden rörelse eller fysisk aktivitet får mig att känna mig märkbart bättre.", element: "wood", category: "constitution" },
  { id: 6, text: "Jag fattar gärna beslut snabbt och tycker illa om långvarig obeslutsamhet.", element: "wood", category: "constitution" },
  { id: 7, text: "Stress och frustration påverkar ofta min mage, aptit eller matsmältning.", element: "wood", category: "stress" },
  { id: 8, text: "Jag värdesätter självständighet och tycker om att kunna välja min egen väg.", element: "wood", category: "constitution" },
  { id: 9, text: "Kontakt med andra människor ger mig ofta energi.", element: "fire", category: "constitution" },
  { id: 10, text: "Jag uttrycker vanligtvis mina känslor ganska öppet och tydligt.", element: "fire", category: "constitution" },
  { id: 11, text: "Jag blir lätt entusiastisk och kan snabbt inspireras av nya idéer.", element: "fire", category: "constitution" },
  { id: 12, text: "När mycket händer har jag ibland svårt att varva ner mentalt.", element: "fire", category: "stress" },
  { id: 13, text: "Vid stress kan jag bli rastlös, överstimulerad eller mentalt uppjagad.", element: "fire", category: "stress" },
  { id: 14, text: "Humor, samtal och gemenskap är viktiga delar av mitt välbefinnande.", element: "fire", category: "constitution" },
  { id: 15, text: "Om jag håller ett högt tempo länge känner jag att min energi snabbt kan bli uttömd.", element: "fire", category: "stress" },
  { id: 16, text: "Jag tycker om att skapa kontakt, värme och engagemang omkring mig.", element: "fire", category: "constitution" },
  { id: 17, text: "Jag har en naturlig tendens att hjälpa, stötta och ta hand om andra.", element: "earth", category: "constitution" },
  { id: 18, text: "När något bekymrar mig kan jag tänka på samma sak om och om igen.", element: "earth", category: "stress" },
  { id: 19, text: "Stabilitet, regelbundna rutiner och trygghet är viktiga för mig.", element: "earth", category: "constitution" },
  { id: 20, text: "Min matsmältning fungerar sämre när jag äter oregelbundet eller under stress.", element: "earth", category: "stress" },
  { id: 21, text: "När jag är ur balans kan jag känna mig tung, trög eller ovanligt energilös.", element: "earth", category: "stress" },
  { id: 22, text: "Jag uppskattar praktiska uppgifter där jag konkret kan hjälpa andra.", element: "earth", category: "constitution" },
  { id: 23, text: "Jag föredrar ofta stabil förändring framför plötsliga och stora förändringar.", element: "earth", category: "constitution" },
  { id: 24, text: "Jag tar lätt ansvar för familj, vänner eller människor omkring mig.", element: "earth", category: "constitution" },
  { id: 25, text: "Jag uppskattar ordning, struktur och tydliga principer.", element: "metal", category: "constitution" },
  { id: 26, text: "Jag tycker att tydliga gränser och ansvarsfördelningar är viktiga.", element: "metal", category: "constitution" },
  { id: 27, text: "När jag är stressad kan jag bli överdrivet kritisk eller perfektionistisk.", element: "metal", category: "stress" },
  { id: 28, text: "Jag kan ha svårt att släppa sådant som jag tycker borde ha blivit annorlunda.", element: "metal", category: "stress" },
  { id: 29, text: "Jag uppskattar kvalitet, precision och att saker görs ordentligt.", element: "metal", category: "constitution" },
  { id: 30, text: "Jag trivs ofta bättre när min omgivning känns ren, organiserad och överskådlig.", element: "metal", category: "constitution" },
  { id: 31, text: "Sorg, besvikelse eller förlust kan påverka mig under lång tid.", element: "metal", category: "stress" },
  { id: 32, text: "Jag tycker om att avsluta, förfina och skapa struktur i sådant som andra har påbörjat.", element: "metal", category: "constitution" },
  { id: 33, text: "Jag brukar observera och tänka efter innan jag agerar.", element: "water", category: "constitution" },
  { id: 34, text: "Jag är naturligt mån om att hushålla med min energi och mina resurser.", element: "water", category: "constitution" },
  { id: 35, text: "Jag dras ofta till djupa frågor, kunskap och sådant som ligger under ytan.", element: "water", category: "constitution" },
  { id: 36, text: "Vid osäkerhet eller rädsla har jag en tendens att dra mig tillbaka.", element: "water", category: "stress" },
  { id: 37, text: "När jag verkligen bestämt mig kan jag vara mycket uthållig.", element: "water", category: "constitution" },
  { id: 38, text: "Jag behöver regelbundet tid för mig själv för att återhämta mig.", element: "water", category: "constitution" },
  { id: 39, text: "Långvarig överansträngning påverkar mig starkt och gör att jag behöver mycket återhämtning.", element: "water", category: "stress" },
  { id: 40, text: "Jag tänker gärna långsiktigt och strategiskt snarare än att bara fokusera på det som händer just nu.", element: "water", category: "constitution" },
];
